
services:
  api:
    build: .
    container_name: braves_board_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    container_name: braves_board_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-braves_board_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: braves_board_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: braves_board_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bangunindo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
  redis_data: