"""add start_time and total_duration to tasks

Revision ID: 1097929dc4bb
Revises: ce178c288beb
Create Date: 2026-04-16 04:29:57.086972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1097929dc4bb'
down_revision: Union[str, None] = 'ce178c288beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_column_board_position', 'columns', ['board_id', 'position'])
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('total_duration', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'total_duration')
    op.drop_column('tasks', 'start_time')
    op.drop_constraint('uq_column_board_position', 'columns', type_='unique')
    # ### end Alembic commands ###
