"""add type in task attachment table

Revision ID: a5a1094f1464
Revises: f492ba6323fa
Create Date: 2026-04-14 09:57:20.278992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a1094f1464'
down_revision: Union[str, None] = 'f492ba6323fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_column_board_position', table_name='columns', postgresql_where='(deleted_at IS NULL)')
    op.add_column('task_attachments', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_attachments', 'type')
    op.create_index('uq_column_board_position', 'columns', ['board_id', 'position'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
