"""update column model

Revision ID: 7e8028280bdf
Revises: f492ba6323fa
Create Date: 2026-04-10 04:48:33.374501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8028280bdf'
down_revision: Union[str, None] = 'f492ba6323fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_columns_position'), 'columns', ['position'], unique=False)
    op.create_unique_constraint('uq_column_board_position', 'columns', ['board_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_column_board_position', 'columns', type_='unique')
    op.drop_index(op.f('ix_columns_position'), table_name='columns')
    # ### end Alembic commands ###
