"""create tasks table

Revision ID: 8e916b03fc20
Revises: 51977000ee4a
Create Date: 2026-04-08 16:25:58.503555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e916b03fc20'
down_revision: Union[str, None] = '51977000ee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_timer_running', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assignee_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_ids'), 'tasks', ['assignee_ids'], unique=False)
    op.create_index(op.f('ix_tasks_column_id'), 'tasks', ['column_id'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_is_timer_running'), 'tasks', ['is_timer_running'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_deleted_at'), 'subtasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subtasks_is_completed'), 'subtasks', ['is_completed'], unique=False)
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_is_completed'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_deleted_at'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_tasks_is_timer_running'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_column_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_ids'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
