services:
  api:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.dev
    container_name: braves_board_backend_test
    ports:
      - "8000:8000"
    volumes:
      - ../../:/usr/src/app
    env_file:
      - ../../src/backend/app/config/env/test.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: braves_board_db_test
    env_file:
      - ../../src/backend/app/config/env/test.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: braves_board_redis_test
    ports:
      - "6379:6379"
    volumes:
      - redis_data_test:/data

volumes:
  postgres_data_test:
  redis_data_test: